name: Smart contract example Deploy

on:
  [push]


jobs:
  deploy-SC-example:
    defaults:
      run:
        working-directory: ./examples/smartContracts/

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"
          cache-dependency-path: ./examples/smartContracts/contracts/package-lock.json

      - name: Install dependencies
        run: npm install

      - name: build
        run: npm run build

      - name: Deploy
        run: |
          if npm run test-smart-contract-example |& grep -q "Contract deployed"; then
            echo "Contracts successfully deployed!"
          else
            echo "Failed to deploy contracts ..."
            exit 1
          fi
        env:
          JSON_RPC_URL_PUBLIC: ${{ secrets.JSON_RPC_URL_PUBLIC }}

          JSON_RPC_URL_PRIVATE: ${{ secrets.JSON_RPC_URL_PUBLIC }}

          DEPLOYER_PRIVATE_KEY: ${{ secrets.WALLET_PRIVATE_KEY }}
