name: (open-rpc) Test OpenRPC spec

on:
  schedule:
    - cron: "0 2 * * *"

env:
  MAINNET_WALLET_TEST_PRIVATE_KEY: ${{ secrets.MAINNET_WALLET_TEST_PRIVATE_KEY }}

jobs:
  test-openrpc-spec:
    defaults:
      run:
        working-directory: ./open_rpc/

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"
          cache-dependency-path: ./open_rpc/

      - name: Install dependencies
        run: |
          npm ci
        working-directory: ./

      - name: Build workspace
        run: |
          npm run build
        working-directory: ./

      - name: Install dependencies
        run: |
          npm ci

      - name: Generate OpenRPC spec
        run: |
          npm run generate

      - name: Test OpenRPC spec
        run: |
          npm run test
